plugins {
    alias(libs.plugins.fabric.loom)
    alias(libs.plugins.minotaur)
}

repositories {
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    minecraft libs.minecraft
    mappings loom.officialMojangMappings()

    modImplementation libs.fabric.loader
    modImplementation libs.fabric.api

    modCompileOnly libs.modmenu
    compileOnly libs.jetbrains.annotations

    implementation project(path: ':common', configuration: 'namedElements')
}


processResources {
    def projectVersion = project.version
    inputs.property "version", projectVersion

    filesMatching("fabric.mod.json") {
        expand "version": projectVersion
    }

    from project(':common').sourceSets.main.resources
}

tasks.named('jar') {
    from(project(':common').sourceSets.main.output)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('sourcesJar') {
    from(project(':common').sourceSets.main.allSource)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "automaticpackage"
    versionNumber = project.version
    versionName = "MC-AutomaticPackage v${project.version} [Fabric]"
    versionType = "release"
    uploadFile = tasks.remapJar
    gameVersions = ["1.21", "1.21.1"]
    loaders = ["fabric"]
    changelog = rootProject.file("CHANGELOG.md").exists() ? rootProject.file("CHANGELOG.md").text : ""

    dependencies {
        required.project "fabric-api"
        optional.project "modmenu"
    }
}
