# Minecraft & Mod properties
minecraft_version=1.21.1
mod_version=1.1.0
maven_group=com.sxnnyside
archives_base_name=automaticpackage

# Loom
loom_version=1.14.7

# Fabric
loader_version=0.16.10
fabric_version=0.103.0+1.21.1
yarn_mappings=1.21.1+build.3

# NeoForge
neoforge_version=21.1.250

# JVM
org.gradle.jvmargs=-Xmx2G
