plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.14.7'
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    
    compileOnly "net.fabricmc:fabric-loader:${project.loader_version}"
    compileOnly "com.google.code.gson:gson:2.10.1"
    compileOnly "org.slf4j:slf4j-api:2.0.9"

    testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()
}
