plugins {
    alias(libs.plugins.fabric.loom)
}

dependencies {
    minecraft libs.minecraft
    mappings loom.officialMojangMappings()

    compileOnly libs.fabric.loader
    compileOnly libs.gson
    compileOnly libs.slf4j.api
    compileOnly libs.jetbrains.annotations

    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
    testCompileOnly libs.jetbrains.annotations
}

test {
    useJUnitPlatform()
}
