modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="automaticpackage"
version="${version}"
displayName="MC-AutomaticPackage"
logoFile="assets/automaticpackage/icon.png"
authors="HoujouSxnnyside"
description='''
Toggle any resource pack on or off with a single keybind or in-game GUI.
'''

[[dependencies.automaticpackage]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.automaticpackage]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="CLIENT"
