plugins {
    alias(libs.plugins.neoforge.moddev)
}

neoForge {
    version = libs.versions.neoforge.get()

    mods {
        "${project.archives_base_name}" {
            sourceSet project.sourceSets.main
            sourceSet project(':common').sourceSets.main
        }
    }

    runs {
        client {
            client()
        }
    }
}

dependencies {
    compileOnly libs.jetbrains.annotations
    implementation project(path: ':common', configuration: 'namedElements')
}

processResources {
    def projectVersion = project.version
    inputs.property "version", projectVersion

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": projectVersion
    }

    from project(':common').sourceSets.main.resources
}

tasks.named('jar') {
    from(project(':common').sourceSets.main.output)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('sourcesJar') {
    from(project(':common').sourceSets.main.allSource)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
