plugins {
    alias(libs.plugins.neoforge.moddev)
    alias(libs.plugins.minotaur)
}

neoForge {
    version = libs.versions.neoforge.get()

    mods {
        "${project.archives_base_name}" {
            sourceSet project.sourceSets.main
            sourceSet project(':common').sourceSets.main
        }
    }

    runs {
        client {
            client()
        }
    }
}

dependencies {
    compileOnly libs.jetbrains.annotations
    implementation project(path: ':common', configuration: 'namedElements')
}

processResources {
    def projectVersion = project.version
    inputs.property "version", projectVersion

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": projectVersion
    }

    from project(':common').sourceSets.main.resources
}

tasks.named('jar') {
    from(project(':common').sourceSets.main.output)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('sourcesJar') {
    from(project(':common').sourceSets.main.allSource)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "automaticpackage"
    versionNumber = project.version
    versionName = "MC-AutomaticPackage v${project.version} [NeoForge]"
    versionType = "release"
    uploadFile = tasks.jar
    gameVersions = ["1.21", "1.21.1"]
    loaders = ["neoforge"]
    changelog = rootProject.file("CHANGELOG.md").exists() ? rootProject.file("CHANGELOG.md").text : ""
}
